### ISSUE TITLE
[Deployer]: CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by marioperezpereira** [RobertGrubb/webpack-s3-deployer#1]
Just initialising with these credentials gives me the error above:

        new WebpackDeployer({
            environments: {
                production: {
                    region: 'xxxx',
                    params: {
                        Bucket: 'xxxx',
                        DistributionId: 'xxx'
                    }
                }
            }
        })

**Comment by marioperezpereira** [comment]
Ok, figured this out:
                    region: 'xxxx',
                    params: {
                        Bucket: 'xxxx',
                        DistributionId: 'xxxx'
                    },
                    accessKeyId: 'xxxx',
                    signatureVersion: 'v3',
                    secretAccessKey: 'xxxx'

**Comment by RobertGrubb** [comment]
Glad to see you got this figured out! Will add this kind of info to the doc soon to be less confusing!

**Comment by marioperezpereira** [comment]
@RobertGrubb it would be nice to have documented also the CDN setup =)
